sudo: required
group: travis_latest
language: rust
rust:
  - stable
os:
  - linux
cache:
  - directories:
    - $HOME/.cargo
    - /nix
before_install:
  - curl -sSf https://nixos.org/nix/install | bash
  - mkdir -p ${HOME}/.nixpkgs
  - echo '{ nix.binaryCaches = ["http://hydra.nixos.org/" "http://cache.nixos.org/"]; }' > ${HOME}/.nixpkgs/config.nix
  - source /home/travis/.nix-profile/etc/profile.d/nix.sh
  - nix-env -iA nixpkgs.capnproto nixpkgs.kcov
install:
  - cargo install --force --git https://github.com/steveeJ/cargo-make.git --branch kcov-remove-arg-quotes
script:
  - cargo make workspace-ci-flow --no-workspace