language: rust
sudo: true
rust:
  - stable
os:
  - linux
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
script:
  - cargo install --debug cargo-make
  - cargo make workspace-ci-flow --no-workspace