sudo: required
group: travis_latest
language: rust
rust:
  - stable
os:
  - linux
cache:
  - cargo
  - directories:
    - /nix
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
before_install:
  - bash <(curl -sSf https://raw.githubusercontent.com/pallavagarwal07/NixCI/master/travis-tests/install-nix.sh)
  - source /home/travis/.nix-profile/etc/profile.d/nix.sh
  - nix-env -iA nixpkgs.capnproto nixpkgs.kcov
script:
  - cargo install --debug cargo-make
  - cargo make workspace-ci-flow